project:
  type: website
  output-dir: docs

website:
  title: "Connor Fair"
  navbar:
    right: 
      - icon: linkedin
        href: "https://www.linkedin.com/in/connor-fair36/"
      - icon: github
        href: "https://github.com/ConnorFair36"

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

execute:
  freeze: true

